-- data types in sql
-- INT => whole number
-- DECIMAL(M, N) => Decimal numbers - Exact value
-- VARCHAR(1) => String of text of length 1
-- BLOB => Binary large object, stores large data
-- DATE => 'YYYY-MM-DD'
-- TIMESTAMP => 'YYYY-MM-DD  HH:MM:SS' - used for recording